version: "3.9"

services:
  frontend:
    build: ./InHouse-Frontend
    container_name: react_ui
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      mern-network:

  backend:
    build: ./inhouse-backend
    container_name: node-api
    restart: always
    ports:
      - "5500:5500"
    depends_on:
      - database
    networks:
      mern-network:

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-backup:/data/db
    networks:
      mern-network:

networks:
  mern-network:
    driver: bridge